
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      compiler: gcc
      env: [linux-debug, BUILD_CONFIGURATION=Debug]
      script: ./builder/scripts/build-linux-make.sh
    - os: linux
      dist: xenial
      sudo: false
      compiler: gcc
      env: [linux-release, BUILD_CONFIGURATION=Release]
      script: ./builder/scripts/build-linux-make.sh
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: [macos-debug, BUILD_CONFIGURATION=Debug]
      script: ./builder/scripts/build-macos-xcode.command
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: [macos-release, BUILD_CONFIGURATION=Release]
      script: ./builder/scripts/build-macos-xcode.command
    - os: windows
      env: [windows-debug, BUILD_CONFIGURATION=Debug]
      script: ./builder/scripts/build-windows-msvc.cmd
    - os: windows
      env: [windows-release, BUILD_CONFIGURATION=Release]
      script: ./builder/scripts/build-windows-msvc.cmd
