language: cpp

matrix:
  include:
    - name: MacOS XCode Debug
      os: osx
      osx_image: xcode10.2
      compiler: clang
      before_script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir build && cd build
        - cmake -G"Xcode" ..
      script:
        - cmake --build . --config Debug
    - name: MacOS XCode Release
      os: osx
      osx_image: xcode10.2
      compiler: clang
      before_script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir build && cd build
        - cmake -G"Xcode" ..
      script:
        - cmake --build . --config Release
    - name: Windows MSVC Debug
      os: windows
      before_script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir build && cd build
        - cmake -G "Visual Studio 15 2017" -A x64 ..
      script:
        - cmake --build . --config Debug
    - name: Windows MSVC Release
      os: windows
      before_script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir build && cd build
        - cmake -G "Visual Studio 15 2017" -A x64 ..
      script:
        - cmake --build . --config Release
    - name: Linux GCC Debug
      os: linux
      dist: xenial
      sudo: false
      compiler: gcc
      addons:
        apt:
          packages:
            - qt5-default
            - qtdeclarative5-dev
            - qtquickcontrols2-5-dev
            - qt5-image-formats-plugins
            - libqt5libqgtk2
            - qtwayland5
            - unixodbc-dev
            - qttranslations5-l10n
            - libqt5svg5
            - libqt5sql5-sqlite
            - libqt5sql5-mysql
            - libqt5sql5-odbc
            - libqt5sql5-psql
            - libwacom-bin
            - libqt5opengl5-dev
      before_script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir build && cd build
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug .. 
      script:
        - cmake --build .
    - name: Linux GCC Release
      os: linux
      dist: xenial
      sudo: false
      compiler: gcc
      addons:
        apt:
          packages:
            - qt5-default
            - qtdeclarative5-dev
            - qtquickcontrols2-5-dev
            - qt5-image-formats-plugins
            - libqt5libqgtk2
            - qtwayland5
            - unixodbc-dev
            - qttranslations5-l10n
            - libqt5svg5
            - libqt5sql5-sqlite
            - libqt5sql5-mysql
            - libqt5sql5-odbc
            - libqt5sql5-psql
            - libwacom-bin
            - libqt5opengl5-dev
      before_script:
        - cd "${TRAVIS_BUILD_DIR}"
        - mkdir build && cd build
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. 
      script:
        - cmake --build .
  